on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  linux:
    name: Linux (CentOS 7)
    runs-on: ubuntu-latest
    container: centos:7

    steps:

    - name: Install
      run: yum install -y gcc gcc-c++ cmake make python3

    - name: Install recent git
      run: |
        yum -y install https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
        yum install -y git

    - name: Install AWS client
      run: |
        curl -O https://bootstrap.pypa.io/pip/3.6/get-pip.py
        python3 get-pip.py --user
        python3 -m pip install awscli --upgrade --user
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Update DuckDB submodule
      run: |
        git config --global --add safe.directory '*'
        make pull

    - name: Build
      run: make release

    - name: Test
      run: make test_release

    - uses: actions/upload-artifact@v2
      with:
        name: substrait-linux
        path: |
          build/release/substrait.duckdb_extension
          

  windows:
    name: Windows (64-bit)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build
      run: |
        make release

    - name: Test
      run: make test_release

    - uses: actions/upload-artifact@v2
      with:
        name: substrait-windows
        path: |
          build/release/substrait.duckdb_extension