on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  mac:
    name: Mac-OS
    runs-on: macos-latest
    env:
      GEN: ninja

    steps:
    - name: Install Ninja
      run: brew install ninja

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Python Dependencies
      shell: bash
      run: |
        pip install pytest pandas "ibis-framework[duckdb]" "ibis-substrait" "substrait-validator" 
        pip uninstall protobuf -y
        pip install --no-binary protobuf protobuf
        pip uninstall duckdb -y
        pip install duckdb --pre

    - name: Update DuckDB submodule
      run: |
        git config --global --add safe.directory '*'
        make pull

    - name: Build DuckDB (Python + R + CLI)
      run: make duckdb_release_all

    - name: Build
      run: make release

    - name: Test
      run: make test_release

    - name: Test Python
      run: |
        (cd test/python && python -m pytest)

    - name: Test R
      run: |
        (cd test/r && R -f dependencies.R)
        (cd test/r && R -f test_substrait.R)