on: [push]

defaults:
  run:
    shell: bash

jobs:
  python:
    name: Python
    runs-on: macos-latest
    env:
      GEN: ninja

    steps:
    - name: Install Ninja
      run: brew install ninja

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Update DuckDB submodule
      run: |
        git config --global --add safe.directory '*'
        make pull

#    - name: Install Python Dependencies
#      shell: bash
#      run: |
#        pip install cibuildwheel twine

    - name: Build DuckDB (Python)
      run: |
        cd duckdb/tools/pythonpkg
        python3 -m pip install .

    - name: Build Substrait
      run: make release

    - name: Install Python Dependencies
      shell: bash
      run: |
        pip install pytest pandas "ibis-framework[duckdb]==3.2.0" "ibis-substrait==2.10.2" "substrait-validator==0.0.8" 
        pip uninstall protobuf -y
        pip install --no-binary protobuf protobuf
#        pip uninstall duckdb -y



    - name: Test Python
      run: |
        (cd test/python && python -m pytest)